#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py collectstatic --noinput
python /app/manage.py migrate
# echo '▬▬ι═══════ﺤ  FALTA HACER LAS MIGRACIONES  -═══════ι▬▬'

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
