version: "3.9"

services:
    django:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        image: django_blog
        container_name: django_blog
        volumes:
            - .:/app:z
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        ports:
            - "8000:8000"
        env_file:
            - ./.envs/.local/.django
            - ./.envs/.local/.postgres
        depends_on:
            - postgres
            # - mailpit
        command: /start
        networks:
            - blog_network

    postgres:
        build:
            context: .
            dockerfile: ./docker/local/postgres/Dockerfile
        image: django_blog_production_postgres
        container_name: django_blog_production_postgres
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
            - local_postgres_data_backups:/backups
        env_file:
            - ./.envs/.local/.postgres
        networks:
            - blog_network

#    mailpit:
#        image: docker.io/axllent/mailpit:latest
#        container_name: my_awesome_project_local_mailpit
#        ports:
#          - "8025:8025"

networks:
    blog_network:
        driver: bridge

volumes:
    static_volume:
    media_volume:
    local_postgres_data: {}
    local_postgres_data_backups: {}