#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

working_dir="$(dirname ${0})"

source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

message_welcome "These are the backups you have got:"

# Use the 'ls' command to list the contents of the directory specified by "${BACKUP_DIR_PATH}".
# The '-lht' options to 'ls' mean:
# - '-l': use a long listing format to display detailed information about each file,
# - '-h': print sizes in human readable format (e.g., KB, MB),
# - '-t': sort by modification time, newest first.
# So, this command will display a detailed, human-readable list of the files in the backup directory, sorted by modification time.
ls -lht "${BACKUP_DIR_PATH}"