# Generated by Django 4.2.13 on 2024-05-27 23:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time at which an object was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time at which an object was modified', verbose_name='updated at')),
            ],
            options={
                'db_table': 'liked_post_info',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time at which an object was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time at which an object was modified', verbose_name='updated at')),
                ('id', models.UUIDField(db_column='post_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='post_image/', verbose_name='post_image')),
                ('is_draft', models.BooleanField(default=False, verbose_name='is_draft')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='published_date')),
                ('url', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='url slug')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='link')),
            ],
            options={
                'db_table': 'post_info',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time at which an object was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time at which an object was modified', verbose_name='updated at')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=20, null=True, unique=True, verbose_name='slug')),
                ('image', models.FileField(blank=True, null=True, upload_to='icons/', verbose_name='image')),
            ],
            options={
                'db_table': 'tag_info',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
