name: Continuous Deployment

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
        
          # Write the SSH private key from the GitHub secret into a file
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/git_to_vm_dig_oce
        
          # Set the permissions of the private key file to be read-write for the owner, and no permissions for others
          chmod 600 ~/.ssh/git_to_vm_dig_oce
        
          # Append the SSH configuration for the target host to the SSH config file
          cat >> ~/.ssh/config << END
          # DEFINE A NEW SSH HOST CONFIGURATION
          Host target
              # SET THE HOSTNAME OF THE TARGET SERVER
              HostName $SSH_HOST
              # SET THE USERNAME FOR THE SSH CONNECTION
              User $SSH_USER
              # SET THE PATH TO THE PRIVATE KEY FILE FOR THE SSH CONNECTION
              IdentityFile ~/.ssh/git_to_vm_dig_oce
              # SET THE LOGGING LEVEL TO ERROR
              LogLevel ERROR
              # DISABLE THE CHECK FOR THE HOST KEY IN THE KNOWN HOSTS FILE
              StrictHostKeyChecking no
          END
      - name: You are here
        run: |
          ssh target "pwd"
      - name: Run deploy
        run: |
          ssh target "cd /home/blog_manager/app && docker compose -f production.yml down && git pull origin main && docker compose -f production.yml up --build -d --remove-orphans"
